sudo: required
language: node_js
node_js:
  - "7"
services: 
  - docker

before_install:
  - docker build -t bacsa/awss3api -f ./awss3api/Dockerfile.dev ./awss3api

script:
  - docker run bacsa/awss3api npm test -- --coverage

after_success:
  - docker build -t bacsa/awss3-frontend ./frontend
  - docker build -t bacsa/awss3-api ./awss3api
  - docker build -t bacsa/awss3-nginx ./nginx

  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker hub
  - docker push bacsa/awss3-frontend
  - docker push bacsa/awss3-api
  - docker push bacsa/awss3-nginx

# deploy:
#   provider: elasticbeanstalk
#   region: "eu-central-1"
#   app: "awss3api"
#   env: "awss3api-env"
#   bucket_name: "elasticbeanstalk-eu-central-1-044016133399"
#   bucket_path: "docker-awss2-api"
#   on:
#     branch: master
#   access_key_id: $TRAVIS_ACCESS_KEY
#   secret_access_key: "$TRAVIS_SECRET_KEY"



