sudo: required
language: node_js
node_js:
  - "7"
services: 
  - docker

before_install:
  - docker build -t awss3api -f Dockerfile .

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-awss2-api"
  env: "docker-awss2-api-env"
  bucket_name: "elasticbeanstalk-eu-central-1-044016133399"
  bucket_path: "docker-awss2-api"
  on:
    branch: master
  access_key_id: $TRAVIS_ACCESS_KEY
  secret_access_key: "$TRAVIS_SECRET_KEY"



