sudo: required
services: 
  - docker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-awss2-api"
  env: "docker-awss2-api-env"
  bucket_name: "elasticbeanstalk-eu-west-1-044016133399"
  bucket_path: "docker-awss2-api"
  on:
    branch: master
  access_key_id: $travis-access-key
  secret_access_key: "$travis-secret-key"



