version: "3"
services:
  awss3api:
    build: ./awss3api
    networks:
      awsnet:
        aliases:
          - awss3-api.local
    volumes: 
      - /app/node_modules
      - ./awss3api:/app
  frontend:
    build: ./frontend
    networks:
      awsnet:
        aliases:
          - awss3-frontend.local
    volumes:
      - /app/node_modules
      - ./frontend:/app
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    networks:
      awsnet:
    command: /bin/bash -c "envsubst  > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  
networks:
  awsnet: